GET http://localhost:3000/api/authors

###
GET http://localhost:3000/api/authors/7

###
POST http://localhost:3000/api/authors
Content-Type: application/json

{
    "first_name": "Oscar",
    "last_name": "Wilde"
}

###
PUT http://localhost:3000/api/authors/13
Content-Type: application/json

{
    "first_name": "Oscar",
    "last_name": "cambio prueba"
}
###
GET http://localhost:3000/api/books

###
GET http://localhost:3000/api/books/4

###
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "name": "bienvenido",
    "ISBN": "78-8987",
    "fk_author": 2
}

###
PUT http://localhost:3000/api/books/11
Content-Type: application/json

{
    "name": "cambio para prueba",
    "ISBN": "78-8987 cambio",
    "fk_author": 3
}
